spring.application.name=ch12-mcp-stdio-client


spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://100.64.80.110:11434}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:qwen3.5:9b}
spring.ai.ollama.chat.temperature=0.3
spring.ai.ollama.chat.num-ctx=8192

# Embedding 설정
spring.ai.ollama.embedding.model=qwen3-embedding:0.6b
spring.ai.ollama.embedding.truncate=true

# Qwen의 Thinking 출력을 끄고 일반 답변만 생성
spring.ai.ollama.chat.think=false


#Logging
logging.level.io.modelcontextprotocol=DEBUG
logging.level.org.springframework.ai=DEBUG


#MCP Setting
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
#spring.ai.mcp.client.stdio.connections.server1.command=java
#spring.ai.mcp.client.stdio.connections.server1.args[0]=-jar
#spring.ai.mcp.client.stdio.connections.server1.args[1]=C:/Users/GGG/Desktop/Workspace/SpringAI/ch12-mcp-stdio-server/build/libs/ch12-mcp-stdio-server-0.0.1-SNAPSHOT.jar