spring.application.name=ch05

# ChatModel을 Ollama로 선택
spring.ai.model.chat=ollama

spring.ai.ollama.base-url=http://100.64.80.110:11434

spring.ai.ollama.chat.model=qwen3.5:9b
spring.ai.ollama.chat.temperature=0.3
spring.ai.ollama.chat.num-ctx=8192
spring.ai.ollama.chat.think=false

# OpenAI 키는 나중에 다시 사용할 수 있도록 유지 가능
spring.ai.openai.api-key=${OPENAI_API_KEY:}

# 정적 콘텐츠 캐시 설정
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

# Thymeleaf 캐시 설정
spring.thymeleaf.cache=false
